<script>
    import { element } from "svelte/internal";


async function getData(type, amount){
    const response = await fetch(`https://random-data-api.com/api/v2/${type}?size=${amount}&response_type=json`, {
        method: 'GET',
        headers:{
            'Content-Type': 'application/json'
        },
    });

    response.text().then(result => {
        manage(JSON.parse(result));
    }, err => {
        console.log(err);
    });
}

function manage(result){
    dataResponse = result;
}

function type(){
    searchQuery = searchBar.value;
}

function viewDetails(index){
    dvData = dataResponse[index];
    console.log(dvData);
}

let dataTypes = [
    'users', 'addresses', 'banks', 'appliances', 'beers', 'blood_types', 'credit_cards'
];
let defaultAmount = 99;
let dataResponse = [];
let searchBar;
let searchQuery = '';
let searchType = 'email'
let dvData; 

getData(dataTypes[0], defaultAmount);
</script>

<nav>
    <a class="back" href="/">Return to main</a>
    <p class="disclaimer">
        *This information is not real. All data generated by 
        <a target="_blank" rel="noopener noreferrer" href="https://random-data-api.com/">random-data-api.com</a>.
    </p>
    <input type="text" on:keyup={type} bind:this={searchBar} placeholder="Search">
    <select>
        <option on:click={()=>{searchType='first_name'}}>First name</option>
        <option on:click={()=>{searchType='last_name'}}>Last name</option>
        <option on:click={()=>{searchType='email'}}>Email</option>
    </select>
</nav>

<br/><br/><br/>

{#if dvData!=undefined}
    <section class="detailedview">
        <h2>
            <span on:keydown={()=>{dvData=undefined}} on:click={()=>{dvData=undefined}}>&#9587;</span> 
            Detailed information
        </h2>
        <table>
            <tr>
                <td>Full name</td>
                <td>{`${dvData.first_name} ${dvData.last_name}`}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{dvData.email}</td>
            </tr>
            <tr>
                <td>Birthdate</td>
                <td>{dvData.date_of_birth}</td>
            </tr>
            <tr>
                <td>Phone</td>
                <td>{dvData.phone_number}</td>
            </tr>
            <tr>
                <td>Job title</td>
                <td>{dvData.employment['title']}</td>
            </tr>
            <tr>
                <td>CC Number</td>
                <td>{dvData.credit_card['cc_number']}</td>
            </tr>
        </table>
        <p>{`${dvData.address['city']}, ${dvData.address['state']}, ${dvData.address['country']}`}</p>
        <p>{`${dvData.address['street_address']}, ${dvData.address['street_name']} ${dvData.address['zip_code']}`}</p>
        <p class="disclaimer">
            *This information is not real. All data generated by 
            <a target="_blank" rel="noopener noreferrer" href="https://random-data-api.com/">random-data-api.com</a>.
        </p>
    </section>
{/if}

<section class="userlist">
    {#each dataResponse as data, index}
        {#if data[searchType].toLowerCase().includes(searchQuery) || searchQuery.length==0}
            <section class="userSection" 
                on:keypress={()=>{viewDetails(index)}} on:click={()=>{viewDetails(index)}}>
                <p>{`${data.first_name} ${data.last_name}`}</p>
                <p>{data.email}</p>
            </section>
        {/if}
    {/each}
</section>

<style>
*{
    font-family: Arial;
    cursor: default;
    user-select: none;
}

nav{
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    height: 42px;
    background: #fdfdfd;
    box-shadow: 0 -1px 3px #2A3951;
    display: table;
}

.userlist{
    display: flex;
    width: 100%;
    justify-content: left;
    flex-wrap: wrap;
    gap: 20px;
    margin: 0 auto;
}

.userSection{
    background: whitesmoke;
    display: inline-block;
    width: 25%;
    min-width: 260px;
    margin: 7px 5px;
    padding: 20px;
    border-radius: 2px;
}
.userSection:hover, .userSection p:hover{
    cursor: pointer;
}

a{
    cursor: pointer;
    color: #2A3951;
    text-decoration: none;
}
a.back{
    display: table-cell;
    font-size: 18px;
    vertical-align: middle;
    position: relative;
    left: 18px;
    width: 200px;
}

nav input, nav select{
    cursor: text;
    caret-color: auto;
    outline: none;
    border: 1px solid #2A3951;
    border-radius: 2px;
    font-size: 16px;
    transform: translateY(4px);
    position: relative;
    float: right;
    padding: 0 8px;
}
nav input{
    height: 28px;
    width: 230px;
    right: 160px;
}
nav select{
    height: 29.5px;
    width: 120px;
    right: -200px;
    border-left: none;
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
}

.detailedview{
    position: fixed;
    height: calc(100% - 43px);
    width: 500px;
    right: 0;
    bottom: 0;
    background: #fdfdfd;
    box-shadow: 0 1px 3px #2A3951;
}

.detailedview h2{
    margin-left: 20px;
}

.detailedview h2 span{
    font-size: 16px;
    position: relative;
    top: -3px;
    left: -3px;
}

.detailedview table, .detailedview p{
    margin-left: 25px;
}

.detailedview table tr{
    height: 24px;
}

.detailedview table tr td{
    min-width: 120px;
}
.detailedview table tr td:last-of-type{
    user-select: all;
}

.disclaimer{
    position: absolute;
    left: 0;
    bottom: 0;
    color: black;
    font-size: 14px;
}
.disclaimer a{
    color: black;
}
nav .disclaimer{
    left: 20%;
    padding: 0;
    margin: 0;
    font-size: 12px;
}

</style>